openapi: 3.0.0
info:
  title: WSO2 Identity Server - Notification Senders API Definition
  description: This document specifies a **RESTful API** for **WSO2 Identity Server Notification Senders**
  contact:
    name: WSO2
    url: http://wso2.com/products/identity-server/
    email: architecture@wso2.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "v1"
servers:
  - url: https://localhost:9443/t/{tenant-domain}/api/server/v1
    variables:
      tenant-domain:
        default: carbon.super
security:
  - OAuth2: []
  - BasicAuth: []
paths:
  /notification-senders/email:
    get:
      tags:
        - Email Senders
      summary: Get a list of email senders
      description: |
        This API provides the capability to retrieve the list of email senders.
      operationId: getEmailSenders
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailProviderList'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Email Senders
      summary: Create an email sender
      description: "This API provides the capability to create an email sender.\n\nIf the 'name' is not not defined, 'EmailPublisher' is taken as the default name."
      operationId: createEmailSender
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailSenderAdd'
      responses:
        "201":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailSender'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /notification-senders/email/{sender-name}:
    get:
      tags:
        - Email Senders
      summary: Retrieve an email sender by name
      description: |
        This API provides the capability to retrieve an email sender by name.
      operationId: getEmailSender
      parameters:
        - name: sender-name
          in: path
          description: name of the email sender
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailSender'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Email Senders
      summary: Update an email sender
      description: |
        This API provides the capability to update an email sender by name.
      operationId: updateEmailSender
      parameters:
        - name: sender-name
          in: path
          description: name of the email sender
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailSenderUpdateRequest'
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailSender'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Email Senders
      summary: Delete an email sender by name
      description: |
        This API provides the capability to delete an email sender by name.
      operationId: deleteEmailSender
      parameters:
        - name: sender-name
          in: path
          description: name of the email sender
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /notification-senders/sms:
    get:
      tags:
        - SMS Senders
      summary: Get a list of SMS senders
      description: |
        This API provides the capability to retrive a list of SMS notification senders.
      operationId: getSMSSenders
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SMSProviderList'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - SMS Senders
      summary: Create a SMS sender
      description: |
        This API provides the capability to create a SMS sender.
        If the 'name' is not not defined, 'SMSPublisher' is taken as the default name.
      operationId: createSMSSender
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SMSSenderAdd'
      responses:
        "201":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SMSSender'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /notification-senders/sms/{sender-name}:
    get:
      tags:
        - SMS Senders
      summary: Get a SMS sender by name
      description: |
        This API provides the capability to retrive a SMS notification sender by name.
      operationId: getSMSSender
      parameters:
        - name: sender-name
          in: path
          description: name of the SMS sender
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SMSSender'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - SMS Senders
      summary: Update a SMS sender
      description: |
        This API provides the capability to update a SMS Sender.
      operationId: updateSMSSender
      parameters:
        - name: sender-name
          in: path
          description: name of the SMS sender
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SMSSenderUpdateRequest'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SMSSender'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - SMS Senders
      summary: Delete a SMS sender by name
      description: |
        This API provides the capability to delete a SMS sender by name.
      operationId: deleteSMSSender
      parameters:
        - name: sender-name
          in: path
          description: name of the SMS sender
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "405":
          description: Method Not Allowed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          example: NSM-00000
        message:
          type: string
          example: Some Error Message
        description:
          type: string
          example: Some Error Description
        traceId:
          type: string
          example: e0fbcfeb-3617-43c4-8dd0-7b7d38e13047
    EmailSenderAdd:
      required:
        - fromAddress
        - password
        - userName
      type: object
      properties:
        name:
          type: string
          example: EmailPublisher
        fromAddress:
          type: string
          example: iam@gmail.com
        userName:
          type: string
          example: iam
        password:
          type: string
          example: iam123
        properties:
          type: array
          example:
            - key: encryption
              value: "true"
            - key: startTLS
              value: true
          items:
            $ref: '#/components/schemas/Properties'
    SMSSenderAdd:
      required:
        - ProviderURL
        - provider
      type: object
      properties:
        name:
          type: string
          example: SMSPublisher
        provider:
          type: string
          example: NEXMO
        providerURL:
          type: string
          example: https://rest.nexmo.com/sms/json
        key:
          type: string
          example: 4cb49374
        secret:
          type: string
          example: Fba3EtqyPg4sgE93
        sender:
          type: string
          example: +94 775563324
        properties:
          type: array
          example:
            - key: HTTPHeaders
              value: application/x-www-form-urlencoded
          items:
            $ref: '#/components/schemas/Properties'
    EmailSender:
      required:
        - fromAddress
        - name
        - password
        - smtpPort
        - smtpServerHost
        - userName
      type: object
      properties:
        name:
          type: string
          example: EmailPublisher
        smtpServerHost:
          type: string
          example: smtp.gmail.com
        smtpPort:
          type: integer
          example: 587
        fromAddress:
          type: string
          example: iam@gmail.com
        userName:
          type: string
          example: iam
        password:
          type: string
          example: iam123
        properties:
          type: array
          example:
            - key: encryption
              value: "true"
            - key: startTLS
              value: true
          items:
            $ref: '#/components/schemas/Properties'
    SMSSender:
      required:
        - ProviderURL
        - name
        - provider
      type: object
      properties:
        name:
          type: string
          example: SMSPublisher
        provider:
          type: string
          example: NEXMO
        providerURL:
          type: string
          example: https://rest.nexmo.com/sms/json
        key:
          type: string
          example: 4cb49374
        secret:
          type: string
          example: Fba3EtqyPg4sgE93
        sender:
          type: string
          example: +94 775563324
        properties:
          type: array
          example:
            - key: HTTPHeaders
              value: application/x-www-form-urlencoded
          items:
            $ref: '#/components/schemas/Properties'
    EmailSenderUpdateRequest:
      required:
        - fromAddress
        - password
        - userName
      type: object
      properties:
        fromAddress:
          type: string
          example: iam@gmail.com
        userName:
          type: string
          example: iam
        password:
          type: string
          example: iam123
        properties:
          type: array
          example:
            - key: encryption
              value: "true"
            - key: startTLS
              value: true
          items:
            $ref: '#/components/schemas/Properties'
    SMSSenderUpdateRequest:
      required:
        - ProviderURL
        - provider
      type: object
      properties:
        provider:
          type: string
          example: NEXMO
        providerURL:
          type: string
          example: https://rest.nexmo.com/sms/json
        key:
          type: string
          example: 4cb49374
        secret:
          type: string
          example: Fba3EtqyPg4sgE93
        sender:
          type: string
          example: +94 775563324
        properties:
          type: array
          example:
            - key: HTTPHeaders
              value: application/x-www-form-urlencoded
          items:
            $ref: '#/components/schemas/Properties'
    Properties:
      required:
        - key
        - value
      type: object
      properties:
        key:
          type: string
        value:
          type: string
      example:
        - key: email
          value: iam@gmail.com
    EmailProviderList:
      type: array
      items:
        $ref: '#/components/schemas/EmailSender'
    SMSProviderList:
      type: array
      items:
        $ref: '#/components/schemas/SMSSender'
  parameters:
    typeQueryParam:
      name: type
      in: query
      description: |
        Type of authenticators. Can be either 'LOCAL' or 'REQUEST_PATH'
      required: false
      style: form
      explode: true
      schema:
        type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://localhost:9443/oauth2/authorize
          tokenUrl: https://localhost:9443/oauth2/token
          scopes: {}